econcs/urls.py
from django.urls import path
from . import views

app_name = "econcs"
urlpatterns = [
    path('', views.to_home, name='to_home'),
    path('home', views.home, name='home'),
    path('people', views.people, name='people'),
    path('publication', views.publication, name='publication'),
    path('teaching', views.teaching, name='teaching'),
    path('seminar', views.seminar, name='seminar'),
    path('news', views.news, name='news'),
]

miseem/urls.py
from django.urls import path
from . import views

app_name = "miseem"
urlpatterns = [
    # /miseem/
    path('', views.to_index, name='to_index'),
    path('index', views.index, name='index'),
    path('example<int:current>', views.example, name='example'),
    path('quiz', views.quiz, name='quiz'),
    path('entry', views.entry, name='entry'),
    path('task', views.task, name='task'),
    path('sorry', views.sorry, name='sorry'),
    path('thanks', views.thanks, name='thanks'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('miseem/', include('miseem.urls'), name = 'miseem'),
    path('econcs/', include('econcs.urls'), name = 'econcs')
]

miseem/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class System(models.Model):
    name = models.CharField(max_length = 64)
    frequence = models.IntegerField(default = 0)

    def __str__(self):
        return self.name

class Question(models.Model):
    description = models.TextField()
    standard = models.TextField()
    frequence = models.IntegerField(default = 0)

    def __str__(self):
        return "<Description: {}>\n<Standard: {}>".format(self.description, self.standard)

class Sentence(models.Model):
    belong_to_system = models.ForeignKey('System', on_delete = models.CASCADE)
    belong_to_question = models.ForeignKey('Question', on_delete = models.CASCADE)
    content = models.TextField()
    frequence = models.IntegerField(default = 0)

    def __str__(self):
        return "<Content: %s>" % self.content

class Answer(models.Model):
    belong_to_noter = models.ForeignKey(User, on_delete = models.CASCADE)
    belong_to_type = models.IntegerField(choices = ((1, 'pointwise'), (2, 'pairwise'), (3, 'listwise')))
    time = models.DateTimeField(auto_now_add = True)
    first = models.ForeignKey('Sentence', related_name = 'first_sentence', on_delete = models.CASCADE)
    second = models.ForeignKey('Sentence', related_name = 'second_sentence', on_delete = models.CASCADE, null = True)
    third = models.ForeignKey('Sentence', related_name = 'third_sentence', on_delete = models.CASCADE, null = True)
    absolute_score = models.IntegerField(choices = set((i, str(i)) for i in range(1, 11)), null = True)
    relative_score = models.IntegerField(choices = ((1, 'Win'), (0, 'Tie'), (-1, 'Lose')), null = True)
    rank_score = models.IntegerField(choices = ((1, '132'), (2, '123'), (3, '231'), (4, '213'), (5, '321'), (6, '312')), null = True)

    def __str__(self):
        if self.belong_to_type == 1:
            return "<Sentence: {}>\n<Score: {}>".format(self.first, self.absolute_score)
        elif self.belong_to_type == 2:
            return "<Sentence1: {}>\n<Sentence2: {}>\n<Score: {}>".format(self.first, self.second, self.relative_score)
        elif self.belong_to_type == 3:
            return "<Sentence1: {}>\n<Sentence2: {}>\n<Sentence3: {}>\n<Score: {}>".format(self.first, self.second, self.thrid, self.rank_score)
        else:
            return "Wrong answer!"

miseem/forms.py
from django.forms import *

class PointWise(Form):
    absolute_score = IntegerField(max_value = 10, min_value = 0)

class PairWise(Form):
    relative_score = ChoiceField(
        choices=((1, 'The first is better.'), (-1, 'The second is better.'), (0, 'I think it is a tie.')),
        widget=RadioSelect
    )

class ListWise(Form):
    rank_score = ChoiceField(
        choices=((1, '132(The first is the best and the second is the worst.)'), 
                (2, '123(The first is the best and the third is the worst.)'),
                (3, '231(The second is the best and the first is the worst.)'),
                (4, '213(The second is the best and the third is the worst.)'),
                (5, '321(The third is the best and the first is the worst.)'),
                (6, '312(The third is the best and the second is the worst.)')),
        widget=RadioSelect
    )

class Quiz(Form):
    money = ChoiceField(
        choices=((0, '$0.5'), (1, '$0.64'), (2, '$1')),
        widget=RadioSelect
    )
    task = ChoiceField(
        choices=((0, '20'), (1, '32'), (2, '48')),
        widget=RadioSelect
    )
    score = ChoiceField(
        choices=((0, 'absolute score'), (1, 'relative score'), (2, 'rank score')),
        widget=RadioSelect
    )
    sentence = ChoiceField(
        choices=((0, '2'), (1, '3'), (2, '4')),
        widget=RadioSelect
    )    

miseem/views.py
from django.shortcuts import render, redirect
from django.http import *
from .models import *
from .forms import *
from django.template import *
from datetime import datetime
from django.db.models import Q
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from random import randint, sample

# Create your views here.

def to_index(request):
    return redirect('miseem:index')

def index(request):
    response = render(request, 'miseem_index.html')
    return response

def example(request, current):
    context = {}
    context['current'] = current
    if current == 1:
        context['head'] = "The 1st example!"
        context['body'] = "This is the first kind of task. You should read the description and the standard answer of the question. Then give the absolute score for the following one sentence. the score range is from 1 to 10."
    elif current == 2:
        context['head'] = "The 2nd example!"
        context['body'] = "This is the second kind of task. You should read the description and the standard answer of the question. Then give the relative score for the following two sentence, the result is limited to three, either one Win or Tie."
    elif current == 3:
        context['head'] = "The 3rd example!"
        context['body'] = "This is the third kind of task. You should read the description and the standard answer of the question. Then give the rank score for the following three sentence, the result is limited to six different order of the three."
    else:
        return render(request, 'sorry.html')
    if request.method == "GET":
        if current == 1:
            total_num = Sentence.objects.count()-1
            chosen_id = randint(0, total_num)
            chosen_sentence = Sentence.objects.all()[chosen_id]
            chosen_question = chosen_sentence.belong_to_question
            context['chosen_sentence'] = [(chosen_sentence.pk, chosen_sentence.content)]
            context['chosen_description'] = chosen_question.description
            context['chosen_standard'] = chosen_question.standard
            context['form'] = PointWise()
        elif current == 2:
            chosen_sentence_list = []
            total_question_num = Question.objects.count()-1
            total_system_num = System.objects.count() - 1
            while len(chosen_sentence_list) < 2:
                chosen_system_list = sample(list(System.objects.all()), 2)
                chosen_system_1 = chosen_system_list[0]
                chosen_system_2 = chosen_system_list[1]
                chosen_question = sample(list(Question.objects.all()), 1)[0]
                chosen_sentence_list = Sentence.objects.filter(belong_to_question = chosen_question).filter(Q(belong_to_system = chosen_system_1) | Q(belong_to_system = chosen_system_2))
            chosen_sentence = sample(list(chosen_sentence_list), 2) 
            chosen_sentence_1 = chosen_sentence[0]
            chosen_sentence_2 = chosen_sentence[1]
            context['chosen_sentence'] = [(chosen_sentence_1.pk, chosen_sentence_1.content), 
                                        (chosen_sentence_2.pk, chosen_sentence_2.content)]
            context['chosen_description'] = chosen_question.description
            context['chosen_standard'] = chosen_question.standard            
            context['form'] = PairWise()
        else:
            chosen_sentence_list = []
            total_question_num = Question.objects.count()-1
            total_system_num = System.objects.count() - 1
            while len(chosen_sentence_list) < 3:
                chosen_system_list = sample(list(System.objects.all()), 3) 
                chosen_system_1 = chosen_system_list[0]
                chosen_system_2 = chosen_system_list[1]
                chosen_system_3 = chosen_system_list[2]
                chosen_question = sample(list(Question.objects.all()), 1)[0]
                chosen_sentence_list = Sentence.objects.filter(belong_to_question = chosen_question).filter(Q(belong_to_system = chosen_system_1) | Q(belong_to_system = chosen_system_2) | Q(belong_to_system = chosen_system_3))
            chosen_sentence = sample(list(chosen_sentence_list), 3) 
            chosen_sentence_1 = chosen_sentence[0]
            chosen_sentence_2 = chosen_sentence[1]
            chosen_sentence_3 = chosen_sentence[2]
            context['chosen_sentence'] = [(chosen_sentence_1.pk, chosen_sentence_1.content), 
                                        (chosen_sentence_2.pk, chosen_sentence_2.content), 
                                        (chosen_sentence_3.pk, chosen_sentence_3.content)]
            context['chosen_description'] = chosen_question.description
            context['chosen_standard'] = chosen_question.standard
            context['form'] = ListWise()
    elif request.method != "POST":
        response = render(request, 'sorry.html')
    response = render(request, 'example.html', context)
    return response

def quiz(request):
    context = {}
    if request.method == "GET":
        context['form'] = Quiz()
    elif request.method == "POST":
        context['form'] = Quiz(request.POST)
        if context['form'].is_valid():
            print(context['form'].cleaned_data)
            money = context['form'].cleaned_data['money']
            task = context['form'].cleaned_data['task']
            score = context['form'].cleaned_data['score']
            sentence = context['form'].cleaned_data['sentence']
            if money != str(1) or task != str(1) or score != str(0) or sentence != str(1):
                return render(request, 'sorry.html')
        else:
            return render(request, 'sorry.html')
    else:
        return render(request, 'sorry.html')
    response = render(request, 'quiz.html', context)
    return response

def entry(request):
    context = {}
    if request.method == "GET":
        if request.user.is_authenticated:
            response = render(request, 'sorry.html')
        else:
            response = render(request, 'entry.html', context)
    elif request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        print(username, password)
        user = authenticate(request, username=username, password=password)
        print(user)
        if user is not None:
            login(request, user)
        else:
            if User.objects.filter(username=username).first() != None:
                return render(request, 'sorry.html')
            user = User.objects.create_user(username=username, password=password)
        response = render(request, 'entry.html', context)
    else:
        response = render(request, 'sorry.html')
    return response

def task(request):
    if not request.user.is_authenticated:
        return render(request, 'sorry.html')
    MAX_ANSWER_NUM = 32
    if request.method == "GET":
        if Answer.objects.filter(belong_to_noter = request.user).count() > MAX_ANSWER_NUM:
            print(Answer.objects.filter(belong_to_noter = request.user).count())
            return render(request, 'sorry.html')
        current = randint(1, 3)
    elif request.method == "POST":
        current = int(request.POST['current'])
    else:
        return render(request, 'sorry.html')
    context = {}
    context['current'] = current
    if current == 1:
        context['head'] = "The 1st kind of task!"
        context['body'] = "This is the first kind of task. You should read the description and the standard answer of the question. Then give the absolute score for the following one sentence. the score range is from 1 to 10."
    elif current == 2:
        context['head'] = "The 2nd kind of task!"
        context['body'] = "This is the second kind of task. You should read the description and the standard answer of the question. Then give the relative score for the following two sentence, the result is limited to three, either one Win or Tie."
    elif current == 3:
        context['head'] = "The 3rd kind of task!"
        context['body'] = "This is the third kind of task. You should read the description and the standard answer of the question. Then give the rank score for the following three sentence, the result is limited to six different order of the three." 
    else:
        return render(request, 'sorry.html')
    if request.method == "GET":  
        if current == 1:
            total_num = Sentence.objects.count()-1
            chosen_id = randint(0, total_num)
            chosen_sentence = Sentence.objects.all()[chosen_id]
            chosen_question = chosen_sentence.belong_to_question
            context['chosen_sentence'] = [(chosen_sentence.pk, chosen_sentence.content)]
            context['chosen_description'] = chosen_question.description
            context['chosen_standard'] = chosen_question.standard
            context['form'] = PointWise()
        elif current == 2:
            chosen_sentence_list = []
            while len(chosen_sentence_list) < 2:
                chosen_system_list = sample(list(System.objects.all()), 2)
                chosen_system_1 = chosen_system_list[0]
                chosen_system_2 = chosen_system_list[1]
                chosen_question = sample(list(Question.objects.all()), 1)[0]
                chosen_sentence_list = Sentence.objects.filter(belong_to_question = chosen_question).filter(Q(belong_to_system = chosen_system_1) | Q(belong_to_system = chosen_system_2))
            chosen_sentence = sample(list(chosen_sentence_list), 2) 
            chosen_sentence_1 = chosen_sentence[0]
            chosen_sentence_2 = chosen_sentence[1]
            context['chosen_sentence'] = [(chosen_sentence_1.pk, chosen_sentence_1.content), 
                                        (chosen_sentence_2.pk, chosen_sentence_2.content)]
            context['chosen_description'] = chosen_question.description
            context['chosen_standard'] = chosen_question.standard            
            context['form'] = PairWise()

miseem/templates/entry.html
{% extends 'miseem_base.html' %}

{% block content %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">
                Entry
            </h3>
        </div>
        <div class="panel-body">
	    For a new user, you have to click the button twice for both register or login!
	    <form action={% url 'miseem:entry' %} method="POST">
		{% csrf_token %}
		<p><label>Username: </label><input type="text" name="username"></p>
		<p><label>Password: </label><input type="password" name="password"></p>
		{% if user.is_authenticated %}
		    <button type="submit" class="btn btn-default" disabled>Register or Login!</button>
		{% else %}
		    <button type="submit" class="btn btn-default">Register or Login!</button>
		{% endif %}
	    </form>
        </div>
    </div>
{% endblock content %}

{% block url %}{% url 'miseem:task' %}{% endblock url%}

{% block button %}
{% if user.is_authenticated %}
    <button type="button" class="btn btn-default">Ready and start!</button>
{% else %}
    <button type="button" class="btn btn-default" disabled>Ready and start!</button>
{% endif %}
{% endblock button %}

miseem/templates/example.html
{% extends 'miseem_base.html' %}

{% block content %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">
                {{ head }}
            </h3>
        </div>
        <div class="panel-body">
		{{ body }}
        </div>
    </div>
{% endblock content %}


{% block form %}
{% ifequal request.method "GET" %}
    <form action={% url 'miseem:example' current %} method="post" class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">
                Decription: {{ chosen_description }}
                <br/>
                Standard: {{ chosen_standard }} 
            </h3>
        </div>
        <div class="panel-body">
            {% csrf_token %}
            <ol class = "list-group">
                {% for sentence in chosen_sentence %}
                    <input type="hidden" name = {{ forloop.counter }} value = {{ sentence.0 }}>
                    <li class = "list-group-item">{{ forloop.counter }}. {{ sentence.1 }}</li>
                {% endfor %}
            </ol>
            {{ form.as_p }}  
        </div>
        <div class="panel-footer">
            <button type="submit" class="btn btn-default">Submit</button>
        </div>
    </form>
{% endifequal %}
{% endblock form %}


{% block url %}
    {% if current != 3 %}
    {% url 'miseem:example' current|add:1 %}
    {% else %}
    {% url 'miseem:quiz' %}
    {% endif %}
{% endblock url%}

{% block button %}
    {% ifequal request.method "POST" %}
        <button type="button" class="btn btn-default">Understand and continue!</button>
    {% endifequal %}
{% endblock button %}

miseem/templates/index.html
{% extends 'base.html' %}

{% block head %}
    <h1>MI-SEEM</h1>
{% endblock head %}

{% block body %}
    <h3>Introduction:</h3>
    <hr>
    <text>context</text>
    <hr>
    <h3>Contact:</h3>
    <hr>
    <text>context</text>
    <hr>
    <a href='example1'>
    <button>agree and continue</button>
    </a>
{% endblock body %}

miseem/templates/miseem_base.html
{% extends 'base.html' %}

{% block body %}
    <div class="page-header">
        <h1 align = "center">MI-SEEM</h1>
    </div>

    <div class="container-fluid">
        <div class="row col-md-8 col-md-offset-2">
            {% block content %}{% endblock content %}
        </div>
        <div class="row col-md-8 col-md-offset-2">
            {% block form %}{% endblock form %}
        </div>
        <div class="row col-md-8 col-md-offset-2">
            <a href={% block url %}{% endblock url %}>
            {% block button %}{% endblock button %}
            </a>
        </div>
    </div>

{% endblock body %}

miseem/templates/miseem_index.html
{% extends 'miseem_base.html' %}

{% block content %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">
                Introduction
            </h3>
        </div>
        <div class="panel-body">
		<p>
		This study compares three different evaluation methods, pointwise, pairwise and listwise.
		Each task contains one question and several answers, you need to give absolute score, relative score or rank score by instruction.
		You should handle exactly 32 tasks to get your money.
		</p>
        </div>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">
                Consent
            </h3>
        </div>
        <div class="panel-body">
            <p>
	    You are being asked to be a volunteer in a research study. Indicate your consent by reading the following document and then clicking the button below.
	    </p>
	    <p>
	    PURPOSE<br>
	    This study compares three different evaluation methods, pointwise, pairwise and listwise. You must be 18 years or older to participate.
            </p>
	    <p>
	    PROCEDURES<br>
	    If you decide to be in this study, your part will involve:
	    This study will take ten to fifteen minutes.
	    You will answer questions using a computer.
	    You will participate in an experiment that has real money at stake.
            </p>
	    <p>
	    RISKS / DISCOMFORTS<br>
	    The following risks/discomforts may occur as a result of you being in this study:
	    There are no foreseeable risks or discomforts associated with your participation in this study.
            </p>
	    <p>
	    PAYMENT TO YOU<br>
	    You will be paid $0.64 for participating in this study.
	    </p>
	    <p>
	    BENEFITS<br>
	    There is no direct benefit expected as a result of you being in this study aside from monetary compensation.
            </p>
	    <p>
	    CONFIDENTIALITY<br>
	    Protecting Your Privacy in this Study
	    All the information we get about you will be kept private.
	    We will do this by not writing down your name or anything else that could link you in any way
	    to the answers you give us for our study. All the study data that we get from you will be kept locked up.
	    If any papers and talks are given about this research, your name will not be used. All data from this study are collected anonymously.
            </p>
	    <p>
	    COSTS TO YOU<br>
	    There are no foreseeable costs to you for your participation in this study.
            </p>
	    <p>
	    ALTERNATIVES<br>
	    Your alternative to being in this study is to simply not participate.
            </p>
	    <p>
	    YOUR RIGHTS AS A RESEARCH SUBJECT<br>
	    Your participation in this study is voluntary.
	    You do not have to be in this study if you don't want to be.
	    You have the right to change your mind and leave the study at any time without giving any reason, and without penalty.
	    Any new information that may make you change your mind about being in this study will be given to you.
	    You do not lose any of your legal rights by signing this consent form.
            </p>
	    <p>
	    QUESTIONS ABOUT THE STUDY OR YOUR RIGHTS AS A RESEARCH SUBJECT<br>
	    If you have any questions, concerns, or complaints about the study, you may contact Charlie, charlie@pku.edu.cn.
	    </p>
        </div>
    </div>
{% endblock content %}

{% block url %}{% url 'miseem:example' 1 %}{% endblock url%}
{% block button %}
    <button type="button" class="btn btn-default">Agree and continue</button>
{% endblock button %}

miseem/templates/quiz.html
{% extends 'miseem_base.html' %}

{% block content %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">
                Quiz
            </h3>
        </div>
        <div class="panel-body">
            According to the intruction, consent and examples, you are supposed to answer these question so that we can make sure you are not a roboot and you are seriously annotating.
        </div>
    </div>
 
{% endblock content %}

{% block form %}
    <form action={% url 'miseem:quiz'%} method="post" class="panel panel-default">
        <div class="panel-body">
            {% csrf_token %}
	    <label>How much will we pay you if you finish the whole?</label>{{form.money}}
            <label>How many tasks you need to answer to finish the whole?</label>{{form.task}}
	    <label>Which score is in the first kind of task?</label>{{form.score}}
	    <label>How many sentenses are there in the third kind of task?</label>{{form.sentence}}
	    {% ifequal request.method "POST" %}
	        <button type="submit" class="btn btn-default" disabled>Submit</button>
	    {% else %}
	        <button type="submit" class="btn btn-default">Submit</button>
	    {% endifequal%}
        </div>
    </form>
{% endblock form %}

{% block url %}{% url 'miseem:entry' %}{% endblock url%}

{% block button %}
{% ifequal request.method "POST" %}
    <button type="button" class="btn btn-default">Finish and continue!</button>
{% else %}
    <button type="button" class="btn btn-default" disabled>Finish and continue!</button>
{% endifequal %}
{% endblock button %}

miseem/templates/reference.html
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html";charset="utf-8" />
</head>
<body>

    <div style="line-height:23px">
    <header>
    <h1>统一建模语言理论测试</h1>
    <form>
    <label>考试科目：统一建模语言</label><br/>
    <label>时间：100分钟</label><br/>
    <label>得分：</label><br/>
    <label>班级（必填）：<input type="text"/></label><br/>
    <label>学号（必填）：<input type="text"/></label><br/>
    <label>姓名（必填）：<input type="text"/></label><br/>
    </form>
    </header>

    <article>
    <form>
    <h4>一、填空题（每空5分，共20分）</h4>
    <ol>
    <li>UML的中文全称是：</li>
    <input type="type"/>
    <li>对象最突出的特征是：</li>
    <input type="type"/> <input type="type"/> <input type="type"/>
    </ol>
    </form>
    </article>

    <article>
    <form>
    <h4>二、选择题（每题10分，共20分）</h4>
    <ol>
        <li>
            <span> UML与软件工程的关系是：</span>
            <div><input type="radio" name="selectOne-1" value="A">(A)UML就是软件工程</div>
            <div><input type="radio" name="selectOne-1" value="B">(B)UML参与到软件工程中软件开发过程的几个阶段</div>
            <div><input type="radio" name="selectOne-1" value="C">(C)UML与软将工程无关</div>
            <div><input type="radio" name="selectOne-1" value="D">(D)UML是软件工程的一部分</div>
        </li>
        <li>
            <span>Java语言支持：</span>
            <div><input type="radio" name="selectOne-2" value="A">(A)单继承</div>
            <div><input type="radio" name="selectOne-2" value="B">(B)多继承</div>
            <div><input type="radio" name="selectOne-2" value="C">(C)单继承和多继承都支持</div>
            <div><input type="radio" name="selectOne-2" value="D">(D)单继承和多继承都不支持</div>
        </li>
    </ol>
    </form>
    </article>

    <article>
    <form>
    <h4>三、多项选择题（每题10分，共20分）</h4>
    <ol>
    <li>用例的粒度分为以下哪三种：</li>  
    <label><input type="checkbox"/>(A)概述级</label><br/>
    <label><input type="checkbox"/>(B)需求级</label><br/>
    <label><input type="checkbox"/>(C)用户目标级</label><br/>
    <label><input type="checkbox"/>(D)子功能级</label><br/>
    <li>类图由以下哪三部分组成：</li>
    <label><input type="checkbox"/>(A)名称(Name)</label><br/>
    <label><input type="checkbox"/>(B)属性(Attribute)</label><br/>
    <label><input type="checkbox"/>(C)操作(Operation)</label><br/>
    <label><input type="checkbox"/>(D)方法(Function)</label><br/>
    </ol>
    </form>
    </article>

    <article>
    <form>
    <h4>四、判断题（每题10分，共20分）</h4>  
    <ol>
    <li>用例图只是用于和客户交流沟通的，用于确定需求。<input type="radio"/><input type="radio"/></li>
    <li>在状态图中，终止状态在一个状态图中允许有任意多个。<input type="radio"/><input type="radio"/></li>
    </ol>
    </form>
    </article>

    <article>
    <form>
    <h4>五、简答题（每题20分，共20分）</h4>  
    <ol>
    <li>简述什么是模型以及模型的表现形式？<textarea cols="20" rows="5"></textarea></li>  
    </ol>
    </form>
    </article>

    <button>计算分数</button>
    <hr/>
    </div>

</body>
</html>

miseem/templates/sorry.html
{% extends 'miseem_base.html' %}

{% block content %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">
                Sorry!
            </h3>
        </div>
        <div class="panel-body">
            Something is Wrong!
        </div>
    </div>
{% endblock content %}

{% block url %}{% url 'miseem:index' %}{% endblock url%}

{% block button %}
    <button type="button" class="btn btn-default">Quit and return!</button>
{% endblock button %}

miseem/templates/task.html
{% extends 'miseem_base.html' %}

{% block content %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">
		{{ head }}
            </h3>
        </div>
        <div class="panel-body">
		{{ body }}
        </div>
    </div>
{% endblock content %}

{% block form %}
{% ifequal request.method "GET" %}
    <form action={% url 'miseem:task'%} method="post" class="panel panel-default">
        {% csrf_token %}
        <div class="panel-heading">
            <h3 class="panel-title">
                Description: {{ chosen_description }}
                <br/>
                Standard: {{ chosen_standard }} 
            </h3>
        </div>
        <div class="panel-body"> 
            <input type="hidden" name = "current" value = {{ current }}>
            <ol class = "list-group">
                {% for sentence in chosen_sentence %}
                    <input type="hidden" name = {{ forloop.counter }} value = {{ sentence.0 }}>
                    <li class = "list-group-item">{{ forloop.counter }}. {{ sentence.1 }}</li>
                {% endfor %}
            </ol>
            {{ form.as_p }}
        </div>
        <div class="panel-footer">
            <button type="submit" class="btn btn-default">Submit</button>
        </div>
    </form>
{% else %}
    {{ form.errors }}
{% endifequal %}
{% endblock form %}


{% block url %}
    {% ifequal request.method "POST" %}
        {% if done %}
            {% url 'miseem:thanks' %}
        {% else %}
            {% url 'miseem:task' %}
        {% endif %}
    {% endifequal %}
{% endblock url%}

{% block button %}
    {% ifequal request.method "POST" %}
        <button type="button" class="btn btn-default">Finish and continue!</button>
    {% endifequal %}
{% endblock button %}

miseem/templates/thanks.html
{% extends 'miseem_base.html' %}

{% block content %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">
                Well done!
            </h3>
        </div>
        <div class="panel-body">
            Thanks for your participation!
        </div>
    </div>
{% endblock content %}

{% block url %}{% url 'miseem:index' %}{% endblock url%}
{% block button %}
    <button type="button" class="btn btn-default">Quit and return!</button>
{% endblock button %}