econcs/urls.py
from django.urls import path
from . import views

app_name = "econcs"
urlpatterns = [
    path('', views.to_home, name='to_home'),
    path('home', views.home, name='home'),
    path('people', views.people, name='people'),
    path('publication', views.publication, name='publication'),
    path('teaching', views.teaching, name='teaching'),
    path('seminar', views.seminar, name='seminar'),
    path('news', views.news, name='news'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('miseem/', include('miseem.urls'), name = 'miseem'),
    path('econcs/', include('econcs.urls'), name = 'econcs')
]

econcs/models.py
from django.db import models

# Create your models here.

econcs/views.py
from django.shortcuts import *
from django.http import *

# Create your views here.

def to_home(request):
    response = redirect('econcs:home')
    return response

def home(request):
    response = render_to_response('home.html')
    return response

def people(request):
    response = render_to_response('people.html')
    return response

def publication(request):
    response = render_to_response('publication.html')
    return response

def teaching(request):
    response = render_to_response('teaching.html')
    return response

def seminar(request):
    response = render_to_response('seminar.html')
    return response

def news(request):
    response = render_to_response('news.html')
    return response

econcs/templates/econcs_base.html
{% extends 'base.html' %}

{% load static %}

{% block body %}
    <div class = "container-fluid" align="center">
        <a href={% url 'econcs:home' %}>
            <img alt = "Logo" src = {% static "images/head_logo.png" %} width = "512px">
        </a> 
    </div>
    <nav class="navbar navbar-default">
        <div class="container row col-sm-8 col-sm-offset-2">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href = {% url 'econcs:home' %}>
                    <img alt="Icon" src={% static "images/head_icon.jpg" %} width = "32px" height = "24px">
                </a>
            </div>
            <div class="collapse navbar-collapse" id="navbar-collapse" style="padding-top: 5px;">
                <ul class="nav nav-pills">
                    <li role="presentation" class="{% block nav_home_active %}{% endblock nav_home_active %}"><a href={% url 'econcs:home' %}>Home</a></li>
                    <li role="presentation" class="{% block nav_people_active %}{% endblock nav_people_active %}"><a href={% url 'econcs:people' %}>People</a></li>
                    <li role="presentation" class="{% block nav_publication_active %}{% endblock nav_publication_active %}"><a href={% url 'econcs:publication' %}>Publication</a></li>.
                    <li role="presentation" class="{% block nav_teaching_active %}{% endblock nav_teaching_active %}"><a href={% url 'econcs:teaching' %}>Teaching</a></li>
                    <li role="presentation" class="{% block nav_seminar_active %}{% endblock nav_seminar_active %}"><a href={% url 'econcs:seminar' %}>Seminar</a></li>
                    <li role="presentation" class="{% block nav_news_active %}{% endblock nav_news_active %}"><a href={% url 'econcs:news' %}>News</a></li>
                </ul>
            </div>
        </div>
    </nav>
    {% block content %}{% endblock content %}
{% endblock body %}

econcs/templates/home.html
{% extends 'econcs_base.html' %}

{% block nav_home_active %}active{% endblock nav_home_active %}

{% block content %}
    <div class = "container-fluid">
        <div class="row">
            <div class="col-sm-8 col-sm-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">
                            Brief Introduction
                        </h3>
                    </div>
                    <div class="panel-body">
                        EconCS@PKU group is based on the Center on Frontiers of Computing Studies (CFCS), Peking University. We are interested in the interdisciplinary research of computer science, economics, and social science in general. The focus of our current work is to build methodologies and systems with cutting-edge technologies from game theory, machine learning, statistics, information theory, randomized algorithms, cryptography and social economic theory. Areas of research include applications of the new methodologies/systems to a variety of social/economic topics, such as market design, crowdsourcing, internet economics, online education, linguistics, anthropology, etc.
                        <br>
                        Current interests:
                        <ul>
                            <li>Social economic science</li>
                            <li>Large market design</li>
                            <li>Equilibrium computation</li>
                            <li>Multi-agent Information System</li>
                            <li>Block-chain economics</li>
                        </ul>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">
                            News
                        </h3>
                    </div>                    
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

econcs/templates/news.html
{% extends 'econcs_base.html' %}

{% block nav_news_active %}active{% endblock nav_news_active %}

{% block content %}

{% endblock content %}

econcs/templates/people.html
{% extends 'econcs_base.html' %}
{% load static %}

{% block nav_people_active %}active{% endblock nav_people_active %}

{% block content %}
    <div class = "container-fluid">
        <div class="row">
            <div class="col-sm-2 col-sm-offset-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">
                            Professor
                        </h3>
                    </div>          
                    <div class="panel-body">
                        <img src = {% static "images/dengxiaotie.jpg" %} alt="邓小铁" width = "100%" height = "100%">
                    </div>
                    <div class="panel-footer">
                        <a href = https://cfcs.pku.edu.cn/faculty/full_time_faculty/dengxiaotie/ >Xiaotie Deng</a>
                    </div>             
                </div>
            </div>
            <div class="col-sm-2">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">
                            Assistant Professor
                        </h3>
                    </div>          
                    <div class="panel-body">
                        <img src = {% static "images/kongyuqing.jpg" %} alt="孔雨晴"  width = "100%" height = "100%">
                    </div>
                    <div class="panel-footer">
                        <a href = https://cfcs.pku.edu.cn/faculty/full_time_faculty/yuqkong/ >Yuqing Kong </a>
                    </div>                    
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-2 col-sm-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">
                            PhD Student
                        </h3>
                    </div>          
                    <div class="panel-body">
                        <img src = {% static "images/arya.jpg" %} alt="二丫"  width = "100%" height = "100%">
                    </div>
                    <div class="panel-footer">
                        Arya Stark
                    </div>                    
                </div>
            </div>
            <div class="col-sm-2">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">
                            PhD Student
                        </h3>
                    </div>          
                    <div class="panel-body">
                        <img src = {% static "images/bran.jpg" %} alt="布兰"  width = "100%" height = "100%">
                    </div>
                    <div class="panel-footer">
                        Bran Stark
                    </div>                    
                </div>
            </div>
            <div class="col-sm-2">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">
                            PhD Student
                        </h3>
                    </div>          
                    <div class="panel-body">
                        <img src = {% static "images/sansa.jpg" %} alt="珊莎"  width = "100%" height = "100%">
                    </div>
                    <div class="panel-footer">
                        Sansa Stark
                    </div>                    
                </div>
            </div>
            <div class="col-sm-2">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">
                            PhD Student
                        </h3>
                    </div>          
                    <div class="panel-body">
                        <img src = {% static "images/john.jpg" %} alt="琼恩"  width = "100%" height = "100%">
                    </div>
                    <div class="panel-footer">
                        John Snow
                    </div>                    
                </div>
            </div>          
        </div>
    </div>
{% endblock content %}

econcs/templates/publication.html
{% extends 'econcs_base.html' %}

{% block nav_publication_active %}active{% endblock nav_publication_active %}

{% block content %}

{% endblock content %}

econcs/templates/seminar.html
{% extends 'econcs_base.html' %}

{% block nav_seminar_active %}active{% endblock nav_seminar_active %}

{% block content %}

{% endblock content %}

econcs/templates/teaching.html
{% extends 'econcs_base.html' %}

{% block nav_teaching_active %}active{% endblock nav_teaching_active %}

{% block content %}

{% endblock content %}